# Generated by Django 5.0.1 on 2024-06-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_scheduleformdraft_daily_study_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleformdraft',
            name='plan_selection_status',
            field=models.JSONField(null=True),
        ),
    ]
