# Generated by Django 5.0.1 on 2024-06-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_scheduleformdraft_plan_selection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleformdraft',
            name='plan_details',
            field=models.JSONField(null=True),
        ),
    ]
