# Generated by Django 5.0.1 on 2024-06-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_scheduleformdraft_plan_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleFormDraft',
        ),
    ]
