# Generated by Django 5.0.1 on 2024-06-27 16:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudyDatesHours',
            new_name='StudyDateHour',
        ),
    ]
