# Generated by Django 5.0.1 on 2024-06-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privateplan',
            old_name='name',
            new_name='title',
        ),
    ]
