# Generated by Django 5.0.1 on 2024-06-20 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_topic_private_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='private_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.privateplan'),
        ),
    ]
