# Generated by Django 5.0.1 on 2024-06-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_topic_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateplan',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
