# Generated by Django 5.0.1 on 2024-06-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_alter_topic_private_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateplan',
            name='exam_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
