# Generated by Django 5.0.1 on 2024-06-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_privateplan_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateplan',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
