# Generated by Django 5.0.1 on 2024-06-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_privateplan_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privateplan',
            old_name='percentage',
            new_name='fraction',
        ),
    ]
