# Generated by Django 5.0.1 on 2024-06-27 20:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_rename_percentage_privateplan_fraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateplan',
            name='fraction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))]),
        ),
    ]
