# Generated by Django 5.0.1 on 2024-06-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0013_alter_topic_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateplan',
            name='required_hours',
            field=models.FloatField(default=0),
        ),
    ]
