# Generated by Django 5.0.1 on 2024-06-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0014_privateplan_required_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='study_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
