FROM python:3.11

WORKDIR /backend

COPY requirements.txt requirements.txt

RUN apt-get update && apt-get install -y \
    libpq-dev \
    python3-dev \
    gcc

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .

# Gunicorn for production
CMD ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "4"]
